import time      # Helps the computer wait
import random    # Helps the computer pick random numbers
import datetime

class BinaryVM:
    """
    Executes the 8-bit instruction set generated by the compiler.
    Supports Logic, Loops, Advanced Math, and String Manipulation.
    """
    def __init__(self):
        self.memory = {}
        # Stores the result of the last comparison (True/False)
        
        self.lists = {}     # <--- ADD THIS! (Stores lists of data)
        self.dicts = {}     # <--- ADD THIS
        self.flag_cmp = False 

    def run(self, binary_data):
        self.memory = {} 
        self.lists = {}     # <--- ADD THIS! (Clears old lists)
        self.dicts = {}     # <--- ADD THIS
        self.flag_cmp = False
        output = []
        lines = binary_data.strip().split('\n')
        
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            if not line: 
                i += 1
                continue
                
            parts = line.split(' ')
            opcode = parts[0]
            
            # --- LOOP HANDLING ---
            repeat = 1
            if opcode == "01000000": # LOOP
                repeat = int(parts[1], 2)
                i += 1 
                if i >= len(lines): break
                line = lines[i].strip()
                parts = line.split(' ')
                opcode = parts[0]

            for _ in range(repeat):
                try:
                    # ==========================================
                    # GROUP 1: VARIABLES & MEMORY
                    # ==========================================
                    
                    # STORE (00010000)
                    if opcode == "00010000": 
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        
                        # Check if value is int or string?
                        # Simple VM Hack: If next part is long, treat as int, else string?
                        # For now, let's assume INT based on Standard JSON
                        val = int(parts[2+n_len], 2)
                        self.memory[name] = val
                        
                        # STRING SET (00010101)
                    elif opcode == "00010101":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        text = "".join([chr(int(b, 2)) for b in parts[2+n_len:]])
                        self.memory[name] = text
                        

                    # STRING STORE (Custom Opcode for "set msg to 'text'")
                    # You might need to add this to standard.json if not present
                    # For now, let's handle APPEND (00010100)
                    elif opcode == "00010100":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        # The rest is the string to append
                        text_to_append = "".join([chr(int(b, 2)) for b in parts[2+n_len:]])
                        
                        if name in self.memory:
                            self.memory[name] = str(self.memory[name]) + text_to_append
                        else:
                            self.memory[name] = text_to_append
                            
                    # ... inside the loop ...

                    # ==========================================
                    # NEW TRICK: DATA PARSING & UTILS 🛠️
                    # ==========================================

                    # SPLIT STRING (00111100)
                    elif opcode == "00111100":
                        # 1. Read Src Var
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        src = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        # 2. Read Delimiter
                        l2 = int(parts[idx], 2); idx += 1
                        delim = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2
                        # 3. Read Dest List
                        l3 = int(parts[idx], 2); idx += 1
                        dest_list = "".join([chr(int(b, 2)) for b in parts[idx:idx+l3]]); idx += l3

                        if src in self.memory:
                            # Python split logic
                            val_str = str(self.memory[src])
                            self.lists[dest_list] = val_str.split(delim)

                    # JOIN LIST (00111101)
                    elif opcode == "00111101":
                        # 1. Read Src List
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        src_list = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        # 2. Read Delimiter
                        l2 = int(parts[idx], 2); idx += 1
                        delim = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2
                        # 3. Read Dest Var
                        l3 = int(parts[idx], 2); idx += 1
                        dest_var = "".join([chr(int(b, 2)) for b in parts[idx:idx+l3]]); idx += l3

                        if src_list in self.lists:
                            # Python join logic
                            # Convert all items to string first just in case
                            str_list = [str(i) for i in self.lists[src_list]]
                            self.memory[dest_var] = delim.join(str_list)

                    # REPLACE STRING (00111110)
                    elif opcode == "00111110":
                        # 1. Var Name
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        var_name = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        # 2. Old Text
                        l2 = int(parts[idx], 2); idx += 1
                        old_txt = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2
                        # 3. New Text
                        l3 = int(parts[idx], 2); idx += 1
                        new_txt = "".join([chr(int(b, 2)) for b in parts[idx:idx+l3]]); idx += l3

                        if var_name in self.memory:
                            original = str(self.memory[var_name])
                            self.memory[var_name] = original.replace(old_txt, new_txt)

                    # CAST TO INT (10000011)
                    elif opcode == "10000011":
                        l1 = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+l1]])
                        if name in self.memory:
                            try:
                                self.memory[name] = int(self.memory[name])
                            except:
                                self.memory[name] = 0 # Default to 0 on error

                    # CAST TO STRING (10000100)
                    elif opcode == "10000100":
                        l1 = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+l1]])
                        if name in self.memory:
                            self.memory[name] = str(self.memory[name])

                    # GET TIME (10000010)
                    elif opcode == "10000010":
                        l1 = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+l1]])
                        # Get formatted time HH:MM:SS
                        now = datetime.datetime.now().strftime("%H:%M:%S")
                        self.memory[name] = now
                        
                    # ==========================================
                    # NEW TRICK: DICTIONARIES (Maps) 🗺️
                    # ==========================================

                    # CREATE DICT (01111000)
                    elif opcode == "01111000":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        self.dicts[name] = {}

                    # SET KEY (01111001)
                    elif opcode == "01111001":
                        # 1. Dict Name
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        d_name = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        
                        # 2. Key Name
                        l2 = int(parts[idx], 2); idx += 1
                        key = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2
                        
                        # 3. Value
                        l3 = int(parts[idx], 2); idx += 1
                        val = "".join([chr(int(b, 2)) for b in parts[idx:idx+l3]]); idx += l3
                        
                        if d_name in self.dicts:
                            self.dicts[d_name][key] = val
                        else:
                            output.append(f"ERR: Dict '{d_name}' undefined.")

                    # GET KEY (01111010)
                    elif opcode == "01111010":
                        # 1. Dict Name
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        d_name = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        
                        # 2. Key Name
                        l2 = int(parts[idx], 2); idx += 1
                        key = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2
                        
                        # 3. Dest Var
                        l3 = int(parts[idx], 2); idx += 1
                        dest = "".join([chr(int(b, 2)) for b in parts[idx:idx+l3]]); idx += l3

                        if d_name in self.dicts and key in self.dicts[d_name]:
                            self.memory[dest] = self.dicts[d_name][key]
                        else:
                            self.memory[dest] = "NULL"

                    # ==========================================
                    # NEW TRICK: STRING MANIPULATION 🔡
                    # ==========================================

                    # LENGTH (00111000)
                    elif opcode == "00111000":
                        # Src Var
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        src = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        # Dest Var
                        l2 = int(parts[idx], 2); idx += 1
                        dest = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2
                        
                        if src in self.memory:
                            self.memory[dest] = len(str(self.memory[src]))
                        elif src in self.lists:
                            self.memory[dest] = len(self.lists[src])

                    # UPPERCASE (00111001)
                    elif opcode == "00111001":
                        l1 = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+l1]])
                        if name in self.memory:
                            self.memory[name] = str(self.memory[name]).upper()

                    # LOWERCASE (00111010)
                    elif opcode == "00111010":
                        l1 = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+l1]])
                        if name in self.memory:
                            self.memory[name] = str(self.memory[name]).lower()
                            
                            
                    # ==========================================
                    # NEW TRICK: ADVANCED MATH & LOGIC 🧮
                    # ==========================================

                    # ABSOLUTE VALUE (OpCode: 00101010)
                    elif opcode == "00101010":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        if name in self.memory:
                            self.memory[name] = abs(self.memory[name])

                    # MAX (OpCode: 00101011)
                    elif opcode == "00101011":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.memory[name] = max(self.memory[name], val)

                    # MIN (OpCode: 00101100)
                    elif opcode == "00101100":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.memory[name] = min(self.memory[name], val)

                    # SWAP (OpCode: 00010011)
                    elif opcode == "00010011":
                        # Read Var 1
                        l1 = int(parts[1], 2)
                        v1 = "".join([chr(int(b, 2)) for b in parts[2:2+l1]])
                        idx = 2 + l1
                        # Read Var 2
                        l2 = int(parts[idx], 2)
                        idx += 1
                        v2 = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]])
                        
                        # Swap values safely
                        if v1 in self.memory and v2 in self.memory:
                            self.memory[v1], self.memory[v2] = self.memory[v2], self.memory[v1]

                    # GTE (>=)
                    elif opcode == "01010101":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] >= val)

                    # LTE (<=)
                    elif opcode == "01010110":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] <= val)
                            
                            
                    # ==========================================
                    # NEW TRICK: LISTS (Arrays) 📝
                    # ==========================================
                    
                    # CREATE LIST (OpCode: 01110000)
                    elif opcode == "01110000":
                        # 1. Read the name length
                        n_len = int(parts[1], 2)
                        # 2. Read the name (e.g., "myList")
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        # 3. Create an empty list []
                        self.lists[name] = [] 

                    # PUSH TO LIST (OpCode: 01110001)
                    elif opcode == "01110001":
                        # 1. Read list name
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        # 2. Read the value to add
                        val = int(parts[2+n_len], 2)
                        
                        # 3. Add it if the list exists!
                        if name in self.lists:
                            self.lists[name].append(val)
                        else:
                            output.append(f"ERR: List '{name}' does not exist.")

                    # GET FROM LIST (OpCode: 01110010)
                    elif opcode == "01110010":
                        # This one is tricky! It has 3 parts: ListName, VariableName, Index
                        
                        # 1. Read List Name
                        l_len = int(parts[1], 2)
                        list_name = "".join([chr(int(b, 2)) for b in parts[2:2+l_len]])
                        current_idx = 2 + l_len
                        
                        # 2. Read Variable Name (Where to save the result)
                        d_len = int(parts[current_idx], 2)
                        current_idx += 1
                        dest_var = "".join([chr(int(b, 2)) for b in parts[current_idx:current_idx+d_len]])
                        current_idx += d_len
                        
                        # 3. Read the Index Number
                        target_index = int(parts[current_idx], 2)

                        # 4. Perform the magic fetch
                        if list_name in self.lists:
                            # Check if index is safe
                            if 0 <= target_index < len(self.lists[list_name]):
                                val = self.lists[list_name][target_index]
                                self.memory[dest_var] = val
                            else:
                                output.append(f"ERR: Index {target_index} is too big!")
                        else:
                            output.append(f"ERR: List '{list_name}' not found.")
                            
                    # PUSH VARIABLE TO LIST (01110011)
                    elif opcode == "01110011":
                        # 1. Read List Name
                        idx = 1
                        l1 = int(parts[idx], 2); idx += 1
                        list_name = "".join([chr(int(b, 2)) for b in parts[idx:idx+l1]]); idx += l1
                        
                        # 2. Read Source Variable Name
                        l2 = int(parts[idx], 2); idx += 1
                        src_var = "".join([chr(int(b, 2)) for b in parts[idx:idx+l2]]); idx += l2

                        if list_name in self.lists:
                            if src_var in self.memory:
                                # Get value from memory and push to list
                                val = self.memory[src_var]
                                self.lists[list_name].append(val)
                            else:
                                output.append(f"ERR: Variable '{src_var}' undefined.")
                        else:
                            output.append(f"ERR: List '{list_name}' undefined.")
                        
                    # ==========================================
                    # NEW TRICK: SPECIAL POWERS ✨
                    # ==========================================

                    # WAIT / SLEEP (OpCode: 10000000)
                    elif opcode == "10000000":
                        sec = int(parts[1], 2)
                        # Safety: Don't wait longer than 5 seconds!
                        if sec > 5: sec = 5
                        time.sleep(sec)

                    # RANDOM NUMBER (OpCode: 10000001)
                    elif opcode == "10000001":
                        # 1. Read Variable Name
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        
                        # 2. Read Min and Max values
                        min_val = int(parts[2+n_len], 2)
                        max_val = int(parts[3+n_len], 2)
                        
                        # 3. Roll the dice!
                        self.memory[name] = random.randint(min_val, max_val)
                        

                    # ==========================================
                    # GROUP 2: MATH
                    # ==========================================
                    
                    elif opcode.startswith("0010"): 
                        # DEC (00101001) - Decrement
                        if opcode == "00101001":
                            n_len = int(parts[1], 2)
                            name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                            if name in self.memory:
                                self.memory[name] -= 1
                        
                        # INC (00101000) - Increment
                        elif opcode == "00101000":
                            n_len = int(parts[1], 2)
                            name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                            if name in self.memory:
                                self.memory[name] += 1

                        # Standard Math (ADD, SUB, MUL, DIV)
                        else:
                            n_len = int(parts[1], 2)
                            name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                            val = int(parts[2+n_len], 2)
                            
                            if name in self.memory:
                                if opcode == "00100001": self.memory[name] += val # ADD
                                if opcode == "00100010": self.memory[name] -= val # SUB
                                if opcode == "00100011": self.memory[name] *= val # MUL
                                if opcode == "00100100": self.memory[name] //= val # DIV
                                if opcode == "00100110": self.memory[name] %= val # MOD
                    
                    # ==========================================
                    # GROUP 3: LOGIC & COMPARISON
                    # ==========================================
                    
                    # IF GREATER (01010011)
                    elif opcode == "01010011":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] > val)
                        else:
                            self.flag_cmp = False

                    # IF LESS (01010100)
                    elif opcode == "01010100":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] < val)
                        else:
                            self.flag_cmp = False
                    
                    # IF EQUALS (01010001)
                    elif opcode == "01010001":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] == val)

                    # THEN DO LINES (01100001)
                    # This is tricky. It skips the next N lines if flag is FALSE.
                    # If flag is TRUE, it does nothing (lets execution continue normally).
                    elif opcode == "01100001":
                        lines_to_skip_if_false = int(parts[1], 2)
                        if not self.flag_cmp:
                            # Skip!
                            # We increment 'i' by 'lines_to_skip_if_false'
                            # NOTE: The loop at the end increments i by 1, so we add (N) here
                            # But wait, this is inside a loop 'repeat'. Jumping inside a repeated instruction is dangerous.
                            # For simplicity, JUMP only works if not looped.
                            i += lines_to_skip_if_false

                    # ==========================================
                    # GROUP 4: SYSTEM & IO
                    # ==========================================

                    # PRINT STRING (00110001)
                    elif opcode == "00110001": 
                        text = "".join([chr(int(b, 2)) for b in parts[1:]])
                        output.append(text)

                    # PRINT VAR (00110010)
                    elif opcode == "00110010": 
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        output.append(str(self.memory.get(name, "NULL")))

                    # CLEAR
                    elif opcode == "11110000": 
                        output = ["__CLEAR__"]
                    
                    # ALERT
                    elif opcode == "11111111": 
                        output.append(">> [SYSTEM BELL]")

                except Exception as e:
                    output.append(f"ERR: FAULT AT LINE {i+1} ({opcode})")

            i += 1

        return "\n".join(output)