class BinaryVM:
    """
    Executes the 8-bit instruction set generated by the compiler.
    Supports Logic, Loops, Advanced Math, and String Manipulation.
    """
    def __init__(self):
        self.memory = {}
        # Stores the result of the last comparison (True/False)
        self.flag_cmp = False 

    def run(self, binary_data):
        self.memory = {} 
        self.flag_cmp = False
        output = []
        lines = binary_data.strip().split('\n')
        
        i = 0
        while i < len(lines):
            line = lines[i].strip()
            if not line: 
                i += 1
                continue
                
            parts = line.split(' ')
            opcode = parts[0]
            
            # --- LOOP HANDLING ---
            repeat = 1
            if opcode == "01000000": # LOOP
                repeat = int(parts[1], 2)
                i += 1 
                if i >= len(lines): break
                line = lines[i].strip()
                parts = line.split(' ')
                opcode = parts[0]

            for _ in range(repeat):
                try:
                    # ==========================================
                    # GROUP 1: VARIABLES & MEMORY
                    # ==========================================
                    
                    # STORE (00010000)
                    if opcode == "00010000": 
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        
                        # Check if value is int or string?
                        # Simple VM Hack: If next part is long, treat as int, else string?
                        # For now, let's assume INT based on Standard JSON
                        val = int(parts[2+n_len], 2)
                        self.memory[name] = val
                        
                        # STRING SET (00010101)
                    elif opcode == "00010101":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        text = "".join([chr(int(b, 2)) for b in parts[2+n_len:]])
                        self.memory[name] = text
                        

                    # STRING STORE (Custom Opcode for "set msg to 'text'")
                    # You might need to add this to standard.json if not present
                    # For now, let's handle APPEND (00010100)
                    elif opcode == "00010100":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        # The rest is the string to append
                        text_to_append = "".join([chr(int(b, 2)) for b in parts[2+n_len:]])
                        
                        if name in self.memory:
                            self.memory[name] = str(self.memory[name]) + text_to_append
                        else:
                            self.memory[name] = text_to_append

                    # ==========================================
                    # GROUP 2: MATH
                    # ==========================================
                    
                    elif opcode.startswith("0010"): 
                        # DEC (00101001) - Decrement
                        if opcode == "00101001":
                            n_len = int(parts[1], 2)
                            name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                            if name in self.memory:
                                self.memory[name] -= 1
                        
                        # INC (00101000) - Increment
                        elif opcode == "00101000":
                            n_len = int(parts[1], 2)
                            name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                            if name in self.memory:
                                self.memory[name] += 1

                        # Standard Math (ADD, SUB, MUL, DIV)
                        else:
                            n_len = int(parts[1], 2)
                            name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                            val = int(parts[2+n_len], 2)
                            
                            if name in self.memory:
                                if opcode == "00100001": self.memory[name] += val # ADD
                                if opcode == "00100010": self.memory[name] -= val # SUB
                                if opcode == "00100011": self.memory[name] *= val # MUL
                                if opcode == "00100100": self.memory[name] //= val # DIV
                                if opcode == "00100110": self.memory[name] %= val # MOD
                    
                    # ==========================================
                    # GROUP 3: LOGIC & COMPARISON
                    # ==========================================
                    
                    # IF GREATER (01010011)
                    elif opcode == "01010011":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] > val)
                        else:
                            self.flag_cmp = False

                    # IF LESS (01010100)
                    elif opcode == "01010100":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] < val)
                        else:
                            self.flag_cmp = False
                    
                    # IF EQUALS (01010001)
                    elif opcode == "01010001":
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        val = int(parts[2+n_len], 2)
                        if name in self.memory:
                            self.flag_cmp = (self.memory[name] == val)

                    # THEN DO LINES (01100001)
                    # This is tricky. It skips the next N lines if flag is FALSE.
                    # If flag is TRUE, it does nothing (lets execution continue normally).
                    elif opcode == "01100001":
                        lines_to_skip_if_false = int(parts[1], 2)
                        if not self.flag_cmp:
                            # Skip!
                            # We increment 'i' by 'lines_to_skip_if_false'
                            # NOTE: The loop at the end increments i by 1, so we add (N) here
                            # But wait, this is inside a loop 'repeat'. Jumping inside a repeated instruction is dangerous.
                            # For simplicity, JUMP only works if not looped.
                            i += lines_to_skip_if_false

                    # ==========================================
                    # GROUP 4: SYSTEM & IO
                    # ==========================================

                    # PRINT STRING (00110001)
                    elif opcode == "00110001": 
                        text = "".join([chr(int(b, 2)) for b in parts[1:]])
                        output.append(text)

                    # PRINT VAR (00110010)
                    elif opcode == "00110010": 
                        n_len = int(parts[1], 2)
                        name = "".join([chr(int(b, 2)) for b in parts[2:2+n_len]])
                        output.append(str(self.memory.get(name, "NULL")))

                    # CLEAR
                    elif opcode == "11110000": 
                        output = ["__CLEAR__"]
                    
                    # ALERT
                    elif opcode == "11111111": 
                        output.append(">> [SYSTEM BELL]")

                except Exception as e:
                    output.append(f"ERR: FAULT AT LINE {i+1} ({opcode})")

            i += 1

        return "\n".join(output)